name: Specs

on: [push]

jobs:
  build:
    environment: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.6, 2.7, 3.0]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install depenencies
      run: |
        gem update --system
        gem install bundler
        bundle install
    - name: Run specs
      run: |
        bundle exec rake
      env:
        CASTLE_API_SECRET: ${{ secrets.CASTLE_API_SECRET }}
    - name: Simplecov Report
      uses: aki77/simplecov-report-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
