name: Specs

on: [push]

jobs:
  build:
    environment: tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # Rails 6.0
          - ruby: "3.1"
            rails: "6.0"
          - ruby: "3.2"
            rails: "6.0"
          # Rails 6.1
          - ruby: "3.1"
            rails: "6.1"
          - ruby: "3.2"
            rails: "6.1"
          # Rails 7.0
          - ruby: "3.1"
            rails: "7.0"
          - ruby: "3.2"
            rails: "7.0"
          # Rails 7.1
          - ruby: "3.1"
            rails: "7.1"
          - ruby: "3.2"
            rails: "7.1"
          - ruby: "3.3"
            rails: "7.1"
          # Rails 7.2
          - ruby: "3.2"
            rails: "7.2"
          - ruby: "3.3"
            rails: "7.2"
          # Rails 8.0
          - ruby: "3.3"
            rails: "8.0"
          - ruby: "3.4"
            rails: "8.0"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        env:
          BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile
        run: |
          bundle config path vendor/bundle
          bundle install
      - name: Run specs
        env:
          BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile
          CASTLE_API_SECRET: ${{ secrets.CASTLE_API_SECRET }}
        run: |
          bundle exec rake
      - name: Simplecov Report
        uses: k1LoW/octocov-action@v1
        if: matrix.ruby == '3.4' && matrix.rails == '8.0'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
