name: Specs

on: [push]

jobs:
  build:
    environment: tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0", "3.1", "3.2", "3.3"]
        rails: ["6.0", "6.1", "7.0", "7.1", "7.2", "8.0"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        env:
          BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile
        run: |
          gem update --system
          bundle config path vendor/bundle
          bundle install
      - name: Run specs
        env:
          BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile
          CASTLE_API_SECRET: ${{ secrets.CASTLE_API_SECRET }}
        run: |
          bundle exec rake
      - name: Simplecov Report
        uses: k1LoW/octocov-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
